// Add polyfills for the browser environment
// Set up global to work in browser context
if (typeof window !== 'undefined') {
  window.global = window;
  window.Buffer = window.Buffer || require('buffer/').Buffer;
}

// Import the canister declarations generated by dfx
import { idlFactory } from '../declarations/civicchain_backend/civicchain_backend.did.js';
import { HttpAgent, Actor } from '@dfinity/agent';

// Get canister ID from Vite environment variables or use local development ID
const CANISTER_ID = import.meta.env.VITE_CANISTER_ID_CIVICCHAIN_BACKEND || 'uxrrr-q7777-77774-qaaaq-cai';

console.log('Initializing ICP with canister ID:', CANISTER_ID);

// Create agent with identity
const createAgent = async () => {
  try {
    console.log('Creating agent...');
    // Vite uses import.meta.env.MODE instead of NODE_ENV
    const isProduction = import.meta.env.MODE === 'production';
    const host = 'http://localhost:4943';  // Always use localhost for now
    console.log('Using host:', host, 'Mode:', import.meta.env.MODE);
    
    // Configure agent with additional browser-friendly options
    const agent = new HttpAgent({ 
      host,
      // Ensure fetch is properly defined for the browser environment
      fetch: typeof window !== 'undefined' ? window.fetch.bind(window) : fetch,
    });

    // Always fetch root key for local development
    if (host.includes('localhost')) {
      console.log('Fetching root key for local development...');
      try {
        await agent.fetchRootKey();
        console.log('Root key fetched successfully');
      } catch (err) {
        console.error('Failed to fetch root key:', err);
        throw new Error('Failed to fetch root key. Make sure dfx is running with `dfx start`');
      }
    }

    return agent;
  } catch (error) {
    console.error('Error creating agent:', error);
    throw new Error('Failed to create agent: ' + error.message);
  }
};

// Create actor with agent
export const createActor = async () => {
  try {
    console.log('Creating actor...');
    const agent = await createAgent();
    console.log('Agent created successfully');
    
    // Add additional configuration for browser environment
    const actor = Actor.createActor(idlFactory, {
      agent,
      canisterId: CANISTER_ID,
      // Improve error handling by specifying a timeout
      callTransform: (args) => ({
        ...args,
        // 5 minute timeout for calls
        ingress_expiry: Math.floor(Date.now() / 1000) + 300,
      }),
    });
    console.log('Actor created successfully');
    return actor;
  } catch (error) {
    console.error('Error creating actor:', error);
    throw new Error('Failed to create actor: ' + error.message);
  }
};

// Initialize actor
let actor = null;
let actorPromise = null;
let lastError = null;

export const getActor = async () => {
  console.log('Getting actor...');
  
  // If we have a cached error, report it
  if (lastError) {
    console.warn('Previous initialization error:', lastError);
  }
  
  // If we don't have a promise or there was a previous error, create a new one
  if (!actorPromise || lastError) {
    console.log('Creating new actor promise...');
    lastError = null; // Reset error state
    
    actorPromise = createActor()
      .then(newActor => {
        console.log('Actor created successfully in promise');
        actor = newActor;
        return actor;
      })
      .catch(error => {
        console.error('Error in actor promise:', error);
        lastError = error; // Store the error
        actorPromise = null; // Reset promise on error
        
        // Enhance error message with troubleshooting info
        const errorMessage = `Failed to initialize Internet Computer connection: ${error.message}. 
        Please check:
        1. Your internet connection
        2. If local development: Is dfx running? Try 'dfx start' in terminal
        3. If production: Is your canister ID correct? Current: ${CANISTER_ID}`;
        
        throw new Error(errorMessage);
      });
  }
  
  return actorPromise;
};

// Export user roles
export const userRoles = [
  { value: 'Citizen', label: 'Citizen' },
  { value: 'Police', label: 'Police Officer' },
  { value: 'BarangayOfficial', label: 'Barangay Official' },
  { value: 'HeadPolice', label: 'Head of Police' },
  { value: 'HeadBarangay', label: 'Head of Barangay' }
];

// Export report types
export const reportTypes = [
  "Pothole",
  "Street Light",
  "Garbage",
  "Traffic",
  "Noise",
  "Vandalism",
  "Suspicious Activity",
  "Other"
];

// Export Manila barangays
export const manilaBarangays = [
  "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5",
  "Barangay 6", "Barangay 7", "Barangay 8", "Barangay 9", "Barangay 10",
  "Barangay 11", "Barangay 12", "Barangay 13", "Barangay 14", "Barangay 15",
  "Barangay 16", "Barangay 17", "Barangay 18", "Barangay 19", "Barangay 20",
  "Ermita", "Intramuros", "Malate", "Paco", "Pandacan",
  "Port Area", "Quiapo", "Sampaloc", "San Andres", "San Miguel",
  "San Nicolas", "Santa Ana", "Santa Cruz", "Santa Mesa", "Tondo",
  "Binondo"
];

// Export Manila police stations
export const manilaPoliceStations = [
  "Manila Police District - Station 1 (Intramuros)",
  "Manila Police District - Station 2 (Ermita)",
  "Manila Police District - Station 3 (Malate)",
  "Manila Police District - Station 4 (Paco)",
  "Manila Police District - Station 5 (Pandacan)",
  "Manila Police District - Station 6 (Quiapo)",
  "Manila Police District - Station 7 (Sampaloc)",
  "Manila Police District - Station 8 (San Miguel)",
  "Manila Police District - Station 9 (Santa Ana)",
  "Manila Police District - Station 10 (Santa Cruz)",
  "Manila Police District - Station 11 (Tondo)",
  "Manila Police District - Station 12 (Binondo)"
];